- params:
    git:
      repoName: org-frogbot
      branches:
        - dev
    scan:
      emailReceivers:
        - vijaygi@jfrog.com
      projects:
        - workingDirs:
            - action
        - workingDirs:
            - .
